version: "3.9"

services:
  AutoClaimBot:
    image: jintaxi/autoclaimbot:latest  # Замените на имя вашего локального образа
    volumes:
      - ./.env:/app/.env:ro
      - ./session_name.session:/app/session_name.session