version: "3.9"

services:
  AutoClaimBot:
    image: jintaxi/autoclaimbot:latest
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro
      - ./session_name.session:/app/session_name.session